# Generated by Django 4.2 on 2023-05-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ManyToManyField(blank=True, help_text="What's the book language", null=True, to='catalog.book', verbose_name='Book Language')),
            ],
        ),
    ]
